### ISSUE TITLE
Need a parameter to set the community string for SNMP traps

### ISSUE THREAD

**Issue by csibbitt** [infrawatch/service-telemetry-operator#148]
Currently it's hardcoded to "public"

**Comment by csibbitt** [comment]
https://github.com/infrawatch/service-telemetry-operator/blob/67a970e10ea455cfba9e58dc19088315462c6f9c/roles/servicetelemetry/templates/manifest_snmp_traps.j2#L23 Needs the same treatment as "Host", and heck, being able to set the port(!) and retries wouldn't be bad either

**Comment by leifmadsen** [comment]
I'm closing this out. I recently made changes that should allow for this.

You can now pass `ansible-playbook -e __service_telemetry_snmptraps_community=private [...] run-ci.yml` to override this in testing, and use `servicetelemetry_vars.alerting.alertmanager.receivers.snmp_traps.community` to override the community in the `ServiceTelemetry` manifest.
