### ISSUE TITLE
quickstart broken with latest changes

### ISSUE THREAD

**Issue by mrunge** [infrawatch/service-telemetry-operator#164]
the service telemetry operator does not install anymore,

in build/stf-run-ci/tasks/setup_stf.yml
for service-telemetry-operator
set channel: stable-1.1 
(instead of channel: latest)

**Comment by mrunge** [comment]
taking this back for a moment, not sure if this is indeed an issue with the available crc version I have (4.5.9); crc does not provide(?) an archive of older versions; the version you currently get is 4.6 which doesn't work with STF due to the certificate manager stuff.

**Comment by mrunge** [comment]
I'm going to give http://mirror.openshift.com/pub/openshift-v4/x86_64/clients/crc/1.17.0/crc-linux-amd64.tar.xz a try, That is 4.5.14.

**Comment by leifmadsen** [comment]
yea we should probably move the channel setting to a variable somewhere that can be passed in... the channels are always going to be changing so we'll need to make it obvious where to change it.

**Comment by mrunge** [comment]
I didn't submit a PR / workaround for this, since this would clearly move into the wrong direction. And in my setup, the marketplace keeps crashing.
