### ISSUE TITLE
Merges to master branch should result in new builds to quay.io

### ISSUE THREAD

**Issue by leifmadsen** [infrawatch/service-telemetry-operator#3]
Update .travis.yml to automatically build the latest CSV and container image, then push them to the appropriate repositories on quay.io when changes are merged to master branch.

**Comment by leifmadsen** [comment]
Resolved

**Comment by leifmadsen** [comment]
Oops doesn't detect changes for pushing CSV changes to quay.io/applications

**Comment by leifmadsen** [comment]
Likely will need to handle the trigger and push of the application CSV part either manually for the time being, or when implemented, do it from the CI system (Travis-CI). Will need to implement the `operator-courier` application and then provide a secret to allow logging into the remote. Robot account should be used. Then provide some logic to check which files were change on merge (and only push on merge to master), and if in `deploy/crds` or `deploy/*.yml` then build a new CSV and push it.

**Comment by mrunge** [comment]
It would also be great if pull requests would create new sao builds somewhere to facilitate easier testing.

**Comment by leifmadsen** [comment]
@mrunge shouldn't be necessary with the new process I developed. Testing needs to be done before submitting patches. See https://docs.engineering.redhat.com/display/CLOUDOPS/Deploy+SAF+Into+Development+Environment
