### ISSUE TITLE
document how to test changes locally

### ISSUE THREAD

**Issue by mrunge** [infrawatch/service-telemetry-operator#30]
Either the documentation here or upstream for the ansible operator could be improved to help reviews here.

**Comment by mrunge** [comment]
For testing like in ansible-operator described:

Dependencies:

* python3-ansible-runner
* python3-kubernetes
* python3-openshift

For pushing the image to the local container registry:
* make sure project sa-telemetry exists
* execute this script
```
operator-sdk build service-assurance-operator:v0.1.1 --image-builder=buildah
podman login -u 'openshift' -p $(oc whoami -t) --tls-verify=false $(oc -n openshift-image-registry get route default-route -o jsonpath='{.spec.host}')
podman tag service-assurance-operator:v0.1.1 $(oc -n openshift-image-registry get route default-route -o jsonpath='{.spec.host}')/sa-telemetry/service-assurance-operator
podman push --tls-verify=false default-route-openshift-image-registry.apps-crc.testing/sa-telemetry/service-assurance-operator

# clean up podman images
podman rmi service-assurance-operator:v0.1.1
podman rmi default-route-openshift-image-registry.apps-crc.testing/sa-telemetry/service-assurance-operator
```

and finally:
```
oc create -f deploy/crds/infra.watch_serviceassurances_crd.yaml
oc create -f deploy/service_account.yaml
oc create -f deploy/role.yaml
oc create -f deploy/role_binding.yaml
export REG=$(oc -n openshift-image-registry get route default-route -o jsonpath='{.spec.host}')
cat deploy/operator.yaml | sed "s|image: quay.io/redhat-service-assurance/service-assurance-operator:latest|image: image-registry.openshift-image-registry.svc:5000/sa-telemetry/service-assurance-operator:latest|" | oc create -f -
# cat deploy/olm-catalog/service-assurance-operator/0.1.0/service-assurance-operator.v0.1.0.clusterserviceversion.yaml | sed "s|image: quay.io/redhat-service-assurance/service-assurance-operator:latest|image: image-registry.openshift-image-registry.svc:5000/sa-telemetry/service-assurance-operator:latest|" | oc create -f -
```
That will at least load and instantiate the SA operator.

You'll also need to create the csv... (to be continued)

**Comment by csibbitt** [comment]
If you get the CSV installing properly (something I'm trying to do right now), then the rest of the `oc create` stuff should not be necessary. What's missing, though, is the cert manager subscription and the OperatorGroup object from https://github.com/redhat-service-assurance/telemetry-framework/blob/master/deploy/quickstart.sh#L22

**Comment by csibbitt** [comment]
@mrunge I got this working after reading this helpful hint: https://bugzilla.redhat.com/show_bug.cgi?id=1744023#c3

The log of my journey is here: https://github.com/redhat-service-assurance/service-assurance-operator/pull/27#issuecomment-576452492

**Comment by leifmadsen** [comment]
Also see https://docs.engineering.redhat.com/display/CLOUDOPS/Deploy+SAF+Into+Development+Environment

**Comment by csibbitt** [comment]
It's not ready for review yet, but I wanted to post that I have started (and hopefully nearly completed) scripting that helps with this

**Comment by leifmadsen** [comment]
The scripting works for this (I've been making heavy use of it for the last 2 issues I've been working on). I might be able to create a bit of upstream documentation to help with this issue as well.

**Comment by leifmadsen** [comment]
#101 mostly solves for this. Would still be nice to maybe port our manual steps from the wiki here.
